import Head from 'next/head' //Head is used for custom meta tags and titles; great for SEO
import Image from 'next/image'
import styles from '../styles/Layout.module.css'
import ArticleList from '../components/ArticleList'

export default function Home({ articles }) {
  return (
    <>
      <Head>
        <title>My Food Forest</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="keywords" content="perennials, food forest" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
           <h1>words</h1>
           <ArticleList articles={articles} />
      </main>
    </>
  )
}

//for data fetching; 3 methods

//For fetching at build time
export const getStaticProps = async () => {
  const res = await fetch(`https://jsonplaceholder.typicode.com/posts?_limit=6`)
  const articles = await res.json()

  return {
    props: {
      articles
    }
  }
}

//for fetching on every request (slower)
//getServersideProps

//getStaticPaths  -to dynamically generate paths based on the data we are fetching