import Head from 'next/head' //Head is used for custom meta tags and titles; great for SEO
import Image from 'next/image'
import styles from '../styles/Layout.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>My Food Forest</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="keywords" content="perennials, food forest" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
           <h1>Perennials</h1>
      </main>
    </>
  )
}