import Head from 'next/head' //Head is used for custom meta tags and titles; great for SEO
import Image from 'next/image'
import styles from '../styles/Layout.module.css'
import Meta from '../components/Meta' // to have different Meta data for the page...
import PerennialContainer from '../containers/PerennialContainer'
import PerennialDetails from '../components/PlantComponents/PerennialDetails'
import { useState } from 'react'


export default function PHome() {
  const [ currentID, setCurrentID ] = useState(null);

  return (
    <>
    <Meta title='perennials' /> 
    {/* this will overwrite the default meta info */}
      <Head>
        <title>Food Forest | Perennials</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="keywords" content="perennials, food forest" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
           <h1>Perennials</h1>
           <div className='mainPlantPage'>
            <PerennialContainer 
              setID={setCurrentID}
              />
            <PerennialDetails 
              currentID={currentID}
            />
           </div>
      </main>
    </>
  )
}